"""Scrape `pi-X.Y-objective` labelled issues from a planning repo into an OBJECTIVES dict."""

import logging
import re
from pathlib import Path

from github import Auth, Github

from dse_oss_reports.objectives import ObjectivesDict

logger = logging.getLogger(__name__)

# PI labels we recognize. Update when a new PI starts being tracked.
_PI_LABELS = (
    "pi-25.2-objective",
    "pi-25.3-objective",
    "pi-25.4-objective",
    "pi-26.1-objective",
    "pi-26.2-objective",
    "pi-26.3-objective",
    "pi-26.4-objective",
)
_PI_LABEL_RE = re.compile(r"pi-(\d+\.\d+)-objective")


def _render_data_module(objectives: ObjectivesDict) -> str:
    """Render an ObjectivesDict as a Python source string assigning ``OBJECTIVES = {...}``.

    The output is intended to be written to a team's ``reports/_objectives_data.py``
    and re-imported. Round-trip through ``exec`` reproduces the input dict exactly.
    """
    lines = [
        "# Quarterly objectives with repos and contributors per objective",
        "# Auto-generated by dse_oss_reports.generator. Do not edit by hand.",
        "# - Objectives: Issues with pi-X.Y-objective labels",
        "# - Contributors: Issue assignees",
        "# - Repos: Labels matching repo:org/repo-name",
        "OBJECTIVES = {",
    ]

    # Sort PIs chronologically (e.g. "pi-25.4" < "pi-26.1")
    sorted_pis = sorted(objectives.keys(), key=lambda x: float(x.split("-")[1]))

    for pi in sorted_pis:
        lines.append(f'    "{pi}": [')

        for obj in sorted(objectives[pi], key=lambda x: x["issue_number"]):
            lines.append("        {")
            lines.append(f'            "issue_number": {obj["issue_number"]},')
            title = obj["title"].replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'            "title": "{title}",')
            lines.append(f'            "state": "{obj["state"]}",')
            lines.append('            "contributors": [')
            for name, username in obj["contributors"]:
                rendered_name = (name or username).replace("\\", "\\\\").replace('"', '\\"')
                lines.append(f'                ("{rendered_name}", "{username}"),')
            lines.append("            ],")
            lines.append('            "repos": [')
            for org, repo in obj.get("repos", []):
                lines.append(f'                ("{org}", "{repo}"),')
            lines.append("            ],")
            lines.append("        },")

        lines.append("    ],")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


class ObjectivesGenerator:
    """Fetch and serialize the OBJECTIVES dataset for a single team's planning repo."""

    def __init__(
        self,
        token: str,
        github_repo: str,
        long_org_name_mapping: dict[str, str] | None = None,
    ) -> None:
        """Configure the generator.

        Args:
            token: A GitHub PAT with ``repo`` and ``read:org`` scope on ``github_repo``.
            github_repo: ``"{org}/{repo}"`` of the team's planning repo.
            long_org_name_mapping: Optional aliases for `repo:` labels whose org name
                exceeds GitHub's label length limit. ``{"cng": "cloudnativegeo"}`` would
                expand a ``repo:cng/zarr-python`` label to ``("cloudnativegeo", "zarr-python")``.
        """
        self.token = token
        self.github_repo = github_repo
        self.long_org_name_mapping = long_org_name_mapping or {}

    def fetch(self) -> ObjectivesDict:
        """Hit the GitHub search API and build an OBJECTIVES dict keyed by ``"pi-X.Y"``."""
        g = Github(auth=Auth.Token(self.token))
        try:
            label_filter = ",".join(_PI_LABELS)
            query = f"repo:{self.github_repo} is:issue label:{label_filter}"
            issues = g.search_issues(query)

            objectives_by_pi: ObjectivesDict = {}
            for issue in issues:
                pi = None
                repos: list[tuple[str, str]] = []
                for label in issue.labels:
                    match = _PI_LABEL_RE.fullmatch(label.name)
                    if match:
                        pi = f"pi-{match.group(1)}"
                        continue
                    if label.name.startswith("repo:"):
                        repo_str = label.name[len("repo:") :]
                        if "/" not in repo_str:
                            continue
                        org, repo_name = repo_str.split("/", 1)
                        org = self.long_org_name_mapping.get(org, org)
                        repos.append((org, repo_name))

                if pi is None:
                    continue

                contributors = [
                    (assignee.name or assignee.login, assignee.login)
                    for assignee in issue.assignees
                ]

                objectives_by_pi.setdefault(pi, []).append(
                    {
                        "issue_number": issue.number,
                        "title": issue.title,
                        "state": issue.state,
                        "contributors": contributors,
                        "repos": repos,
                    }
                )
            for pi_key, objs in sorted(objectives_by_pi.items()):
                repo_count = sum(len(o["repos"]) for o in objs)
                logger.info(
                    "  %s: %d objectives, %d repo mappings", pi_key, len(objs), repo_count
                )
            return objectives_by_pi
        finally:
            g.close()

    def write_data_module(self, path: Path) -> Path:
        """Render the fetched OBJECTIVES dict as a Python source file at ``path``.

        The file is intended to be committed to the consuming repo as
        ``reports/_objectives_data.py``. Returns ``path`` for chaining.
        """
        objectives = self.fetch()
        path.write_text(_render_data_module(objectives))
        logger.info("Wrote %d PIs to %s", len(objectives), path)
        return path
